### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by gzshasha** [sanjusss/aliyun-ddns#20]
the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at Aliyun.Acs.Core.Http.HttpResponse.GetResponse(HttpRequest request, Nullable`1 timeout)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain) in /src/aliyun-ddns/DomainUpdater.cs:line 251

刚开始运行看logs解析记录正常的，运行几天后就会出现以上的错误信息。

![https://i.loli.net/2020/06/17/JpdWKqyRilDx5rf.jpg](https://i.loli.net/2020/06/17/JpdWKqyRilDx5rf.jpg)

**Comment by sanjusss** [comment]
这是阿里云当前endpoint的dns接口有网络问题。
升级容器到0.2.2版本，这个版本会自动选取合适的endpoint，或许可以解决这个问题。

**Comment by gzshasha** [comment]
root@debian:~# docker pull sanjusss/aliyun-ddns
Using default tag: latest
latest: Pulling from sanjusss/aliyun-ddns
Digest: sha256:fb0e61b7164fb4a8bfb337b277bc5d80aa4aace6b4ebba095f1830a72d44e59d
Status: Image is up to date for sanjusss/aliyun-ddns:latest
docker.io/sanjusss/aliyun-ddns:latest

已经是最新的版本了

**Comment by sanjusss** [comment]
是每次获取所有记录时都出错吗？
