### ISSUE TITLE
获取域名的所有记录时出现异常

### ISSUE THREAD

**Issue by imageliu** [sanjusss/aliyun-ddns#28]
大神好：

我遇到问题情况如下：
- 设备：qnap 453b mini
- 网络： 移动ipv6
- 问题：之前可以正常使用，今天发现dns解析没有被修改，问题是获取域名所有记录时出现异常。尝试使用最新版本的镜像，问题仍然存在。似乎和 #20 遇到的问题一样，但是没有看到下文。 

目前采用的的设置如下：

```yml
version: "3"

services:
    aliyun_ddns:
        image: sanjusss/aliyun-ddns:latest
        container_name: aliyun-ddns
        restart: unless-stopped
        network_mode: host
        environment:
            - AKID=XXXXXXXXXX
            - AKSCT=XXXXXXXXXXX
            - DOMAIN=XXX.XXX.fun
            - TYPE=AAAA
```

容器的版本和环境变量：

```
[~] # docker exec -it aliyun-ddns /bin/bash
root@NASXXXXX:/app# dotnet aliyun-ddns.dll --version
aliyun-ddns 0.2.5
root@ NASXXXXX:/app# env
AKID= XXXXXXXXXX
HOSTNAME= NASXXXXX
TYPE=AAAA
ASPNETCORE_URLS=http://+:80
PWD=/app
DOMAIN=XXX.XXX.fun
HOME=/root
AKSCT= XXXXXXXXXX
TERM=xterm
SHLVL=1
DOTNET_RUNNING_IN_CONTAINER=true
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
root@ NASXXXXX:/app#
```

报错：

```log
[07/01/2020 15:23:53]当前公网IPv6为 XXXX: XXXX: XXXX: XXXX: XXXX: XXXX: XXXX: XXXX（ipify.org接口）。
[07/01/2020 15:23:58]获取 XXX.XXX.fun的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: SDK.WebException : HttpWebRequest WebException occured, the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at Aliyun.Acs.Core.Http.HttpResponse.GetResponse(HttpRequest request, Nullable`1 timeout)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[07/01/2020 15:23:58]跳过设置域名 XXX.XXX.fun
```

目前我的域名dns解析记录可以在阿里云手动修改，accesskey 和secret 应该也没有问题，尝试更换别的子用户也不行。。（之前第一次配置的时候，子用户没有开通dns解析权限，似乎会报没有权限的错。。但是现在用新的没有权限的用户的accesskey，报错还是和上文一样）

麻烦大神帮忙看看。

**Comment by sanjusss** [comment]
阿里云dns的api服务器连接问题。连接服务器超时。可能是线路问题。在出现故障的时候，你能打开[http://alidns.aliyuncs.com/](http://alidns.aliyuncs.com/)吗?

**Comment by imageliu** [comment]
刚刚试了一下，好像是nas 自身的网络问题。。。因为可以通过ipv6地址从外网访问，所以没有注意到。。。感谢提醒。

题外话：目前来看，应该是因为我昨天重启过一次路由器，导致了nas本身各种ping不通，localhost都ping不通。。。各种尝试无果，重启nas之后，所有问题解决了。。不知道是不是固定了nas 的局域网ip 的关系。反正，威联通的系统被我用出了windows 的感觉。。。。

再次感谢大神！工具非常好用！
