### ISSUE TITLE
获取test.furry.top的所有记录时出现异常

### ISSUE THREAD

**Issue by zhijun1997** [sanjusss/aliyun-ddns#3]
OS：UNRAID - Docker
```
获取test.furry.top的所有记录时出现异常：System.Xml.XPath.XPathException: Expression must evaluate to a node-set.
   at MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(AstNode qyInput, AxisType axisType, XPathNodeType nodeType)
   at MS.Internal.Xml.XPath.XPathParser.ParseStep(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParsePathExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseExpression(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression(String xpathExpression)
   at MS.Internal.Xml.XPath.QueryBuilder.Build(String query, Boolean allowVar, Boolean allowKey)
   at MS.Internal.Xml.XPath.QueryBuilder.Build(String query, Boolean& needContext)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathExpression.Compile(String xpath)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at System.Xml.XmlDocumentXPathExtensions.SelectNodes(XmlNode node, String xpath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(XmlNode element, String path, Boolean appendPath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(XmlNode element, String path, Boolean appendPath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(String xml, String endpoint)
   at Aliyun.Acs.Core.DefaultAcsClient.ReadError[T](AcsRequest`1 request, HttpResponse httpResponse, Nullable`1 format)
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain) in /src/aliyun-ddns/DomainUpdater.cs:line 294
```
请问这是什么原因？

**Comment by sanjusss** [comment]
请问你传入的参数（除了阿里云的密钥和ID）是什么？
- DOMAIN：需要更新的域名，多个域名需要“,”分隔。
- ENDPOINT：默认为cn-hangzhou，详见定义。
- REDO： 更新间隔，单位秒。建议大于等于TTL/2。
- TTL： 服务器缓存解析记录的时长，单位秒，普通用户最小为600。
- TIMEZONE： 输出日志时的时区，单位小时。
- TYPE： 需要更改的记录类型，可以用“,”隔开，只能是“A”、“AAAA”或“A,AAAA”。

**Comment by zhijun1997** [comment]
问题找到了，原先直接给docker传入的参数照搬写成了“TYPE=A,AAAA”

正确的方法是“TYPE=A” 或者  “TYPE=AAAA” 而不能一起用，现在正常了，谢谢！

**Comment by zhijun1997** [comment]
问题貌似重现了，现在无论是修改TYPE变量为A还是AAAA或者是A,AAAA都出现了Expression must evaluate to a node-set.的问题。

可以帮我看一下吗？谢谢！
![img](https://download.furry.top/img/temp/conf.png)
![img](https://download.furry.top/img/temp/res.png)
![img](https://download.furry.top/img/temp/console.png)

**Comment by sanjusss** [comment]
我看不到你发的图片。
请问你传入的参数（除了阿里云的密钥和ID）是什么？

**Comment by zhijun1997** [comment]
你好，很抱歉很久才回复，我传入的参数是：
-e 'DOMAIN'='@.htips.cn' 
-e 'ENDPOINT'='cn-hangzhou'
-e 'REDO'='30'
-e 'TIMEZONE'='8.0 '
-e 'TTL'='600'
-e 'TYPE'='A,AAAA'

**Comment by zhijun1997** [comment]
@sanjusss 
我使用Console手动运行了一次，完整输出：

`
root@Tower:/app# dotnet aliyun-ddns.dll \
>     -u "LTAI4FiQF7**********" \
>     -p "0IOKWNKDOkMFHoIcG***********" \
>     -d "@.htips.cn" \
>     -e "cn-hangzhou" \
>     -i 30 \
>     -t 60 \
>     --timezone 8.0 \
>     --type A
[10/17/2019 05:16:37]当前公网IPv4为119.130.164.166。
[10/17/2019 05:18:17]检测公网IPv6时发生异常：The operation was canceled.
[10/17/2019 05:18:17]获取@.htips.cn的所有记录时出现异常：System.Xml.XPath.XPathException: Expression must evaluate to a node-set.
   at MS.Internal.Xml.XPath.XPathParser.ParseNodeTest(AstNode qyInput, AxisType axisType, XPathNodeType nodeType)
   at MS.Internal.Xml.XPath.XPathParser.ParseStep(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelativeLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseLocationPath(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParsePathExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseUnionExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseMultiplicativeExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAdditiveExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseRelationalExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseEqualityExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseAndExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseOrExpr(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseExpression(AstNode qyInput)
   at MS.Internal.Xml.XPath.XPathParser.ParseXPathExpression(String xpathExpression)
   at MS.Internal.Xml.XPath.QueryBuilder.Build(String query, Boolean allowVar, Boolean allowKey)
   at MS.Internal.Xml.XPath.QueryBuilder.Build(String query, Boolean& needContext)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathExpression.Compile(String xpath)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at System.Xml.XmlDocumentXPathExtensions.SelectNodes(XmlNode node, String xpath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(XmlNode element, String path, Boolean appendPath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(XmlNode element, String path, Boolean appendPath)
   at Aliyun.Acs.Core.Reader.XmlReader.Read(String xml, String endpoint)
   at Aliyun.Acs.Core.DefaultAcsClient.ReadError[T](AcsRequest`1 request, HttpResponse httpResponse, Nullable`1 format)
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain) in /src/aliyun-ddns/DomainUpdater.cs:line 294
[10/17/2019 05:18:17]跳过设置域名 @.htips.cn
`

**Comment by sanjusss** [comment]
这个异常是阿里云SDK抛出的，我这里无法复现。我已经升级了阿里云SDK的版本，你可以更新容器到0.1.5版再试试看。
再出现错误，你可以尝试：

1. 检查阿里云的密钥和ID是否正确，是否给与了DNS权限。
2. 使用别的ENDPOINT的值试试。

**Comment by zhijun1997** [comment]
谢谢！更新之后已经成功了
