### ISSUE TITLE
不能解析ipv6

### ISSUE THREAD

**Issue by beanhc** [sanjusss/aliyun-ddns#38]
老铁你好，
在unraid（6.8.1）、docker下使用 sanjusss/aliyun-ddns，logs提示不能获取ipv6的地址。
而unraid是分配到ipv6地址的。

[02/26/2021 00:36:09]从 ident.me接口 获取公网IPv6失败。
[02/26/2021 00:36:09]从 dyndns.com接口 获取公网IPv6失败。
[02/26/2021 00:36:09]从 ip.sb接口 获取公网IPv6失败。
[02/26/2021 00:36:09]从 ipify.org接口 获取公网IPv6失败。
[02/26/2021 00:36:09]从 test-ipv6.com接口 获取公网IPv6失败。
[02/26/2021 00:36:09]获取公网IPv6失败，所有API接口均无法返回IPv6地址。
[02/26/2021 00:36:10]成功获取www.beanhc.cc的所有记录，共0条。
[02/26/2021 00:36:10]增加AAAA记录www.beanhc.cc时发生异常： Aliyun.Acs.Core.Exceptions.ClientException: MissingValue : Value is mandatory for this action. + [ RequestId : B4F0C02E-62BF-4C8E-A5FC-20B786055CF2 ]
at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
at Aliyun.Acs.Core.DefaultAcsClient.GetAcsResponse[T](AcsRequest`1 request)
at aliyun_ddns.DomainUpdater.AddRecord(IpType type, String domain, String ip)

**Comment by beanhc** [comment]
不知道什么原因，镜像不能获取宿主机的ipv6地址

**Comment by sanjusss** [comment]
容器的网络模式（network mode）设置为host了吗？

**Comment by beanhc** [comment]
是的
![1](https://user-images.githubusercontent.com/79655944/109286105-ce654600-785c-11eb-83d6-aa4bf5c9446f.png)

**Comment by sanjusss** [comment]
IPv6最好使用直接读取本地地址的方式。同时设置CHECKLOCAL和IPV6NETS，一般IPV6NETS设置为你现在IPv6的地址第一位数字的网段（例如240e::/16）。设置了CHECKLOCAL后就不能通过在线API获取IPv4的公网地址了。

**Comment by sanjusss** [comment]
IPv6最好使用直接读取本地地址的方式。同时设置CHECKLOCAL和IPV6NETS，一般IPV6NETS设置为你现在IPv6的地址第一位数字的网段（例如240e::/16）。设置了CHECKLOCAL后就不能通过在线API获取IPv4的公网地址了。
