### ISSUE TITLE
无法正常解析域名

### ISSUE THREAD

**Issue by zzlinwq** [sanjusss/aliyun-ddns#39]
已经从https://www.namesilo.com/购买域名nas.esir.xyz并转入阿里，但是无法正常解析域名。用的DOCKER版本0.2.7
[03/24/2021 11:54:27]获取nas.esir.xyz的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: InvalidAccessKeyId : Specified access key is not found or invalid. + [ RequestId : 425C0079-8EBB-4416-B69F-F1C36D371682 ]
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[03/24/2021 11:54:27]跳过设置域名 nas.esir.xyz

**Comment by zzlinwq** [comment]
机器是ARM 64位设备

**Comment by sanjusss** [comment]
这里的报错提示是access key id不存在，是不是填错了？

**Comment by zzlinwq** [comment]
docker run -d --restart=always --net=host \
    -e "AKID=LTAYH0osOkH" \
    -e "AKSCT=XW3NVkVJ9Nkglc1R1SdtLGe" \
    -e "DOMAIN=nas.esir.xyz" \
    -e "REDO=30" \
    -e "TTL=60" \
    -e "TIMEZONE=8.0" \
    -e "TYPE=A,AAAA" \
    sanjusss/aliyun-ddns

**Comment by zzlinwq** [comment]
对吗？

**Comment by sanjusss** [comment]
不要暴露自己的key🤦‍，key是否正确需要在阿里云控制台里看。

**Comment by zzlinwq** [comment]
我没暴露，我是说使用docker命令格式和参数是否正确？

**Comment by sanjusss** [comment]
> 我没暴露，我是说使用docker命令格式和参数是否正确？
格式没有问题
