### ISSUE TITLE
今天貌似不行了

### ISSUE THREAD

**Issue by Sohnny0** [sanjusss/aliyun-ddns#44]
[05/17/2021 14:12:08]从 ipip.net接口 获取公网IPv4失败。

[05/17/2021 14:12:08]从 test-ipv6.com接口 获取公网IPv4失败。

[05/17/2021 14:12:08]从 ip-api.com接口 获取公网IPv4失败。

[05/17/2021 14:12:08]从 淘宝接口 获取公网IPv4失败。

[05/17/2021 14:12:08]从 3322接口 获取公网IPv4失败。

[05/17/2021 14:12:08]获取公网IPv4失败，所有API接口均无法返回IPv4地址。

[05/17/2021 14:12:14]获取home.sojpt.com的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: SDK.WebException : HttpWebRequest WebException occured, the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.

   at System.Net.HttpWebRequest.GetResponse()

   at Aliyun.Acs.Core.Http.HttpResponse.GetResponse(HttpRequest request, Nullable`1 timeout)

   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)

   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)

   at aliyun_ddns.DomainUpdater.GetRecords(String domain)

**Comment by sanjusss** [comment]
这是容器无法访问网络了。

**Comment by Sohnny0** [comment]
> 这是容器无法访问网络了。

确实是没网了, 我的其他容器都有, 但奇怪这个今天突然就没网了. 用了好几个月了都没问题. 可能运营商dns的问题吧

**Comment by Sohnny0** [comment]
> 这是容器无法访问网络了。

确实是没网了, 我的其他容器都有, 但奇怪这个今天突然就没网了. 用了好几个月了都没问题. 我重启, 删除容器再重新创建都不行, 怪了

**Comment by sanjusss** [comment]
是qnap的nas吗？我之前用qnap的时候遇到过，重启nas就好了。

**Comment by Sohnny0** [comment]
> 是qnap的nas吗？我之前用qnap的时候遇到过，重启nas就好了。

找到问题了,电信dns服务器的问题.我的宿主机也ping不同百度, 手动设置了其他的dns就好了
