### ISSUE TITLE
DDNS遇到的问题，突然就不能用了，不知道什么原因

### ISSUE THREAD

**Issue by 810517583** [sanjusss/aliyun-ddns#48]
[09/19/2021 00:48:36]当前公网IPv4为 183.7.15.*（ipip.net接口）。
[09/19/2021 00:48:36]获取*.*.online的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: InvalidTimeStamp.Expired : Specified time stamp or date value is expired. + [ RequestId : D2B05C0B-8E52-5C1C-BD81-E71D2B3747B4 ]
at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[09/19/2021 00:48:36]跳过设置域名 *.*.online

**Comment by sanjusss** [comment]
看日志中的描述，应该是本地时间和阿里云的相差过大

**Comment by 810517583** [comment]
> 看日志中的描述，应该是本地时间和阿里云的相差过大

我那时候也有看时间，时间是对的上的，后面删了重装。弄了几次又好了。郁闷
