### ISSUE TITLE
老哥最近好像出问题了，求帮忙看看~

### ISSUE THREAD

**Issue by kingskiss** [sanjusss/aliyun-ddns#50]
[09/30/2021 21:21:12]获取wb2004.top的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: SDK.WebException : HttpWebRequest WebException occured, the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.
at System.Net.HttpWebRequest.GetResponse()
at Aliyun.Acs.Core.Http.HttpResponse.GetResponse(HttpRequest request, Nullable`1 timeout)
at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)
at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[09/30/2021 21:21:12]跳过设置域名 wb2004.top

**Comment by sanjusss** [comment]
错误提示是连接超时，可能是容器内部无法连接到网络。
