### ISSUE TITLE
无法获取IP地址

### ISSUE THREAD

**Issue by YDDDD** [sanjusss/aliyun-ddns#51]
日志如下：

检测公网IPv4时发生异常：The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

环境是群晖里的docker，试了下其他DDNS映像，好像也有问题，所以有可能是本地设置和权限的原因。。

**Comment by YDDDD** [comment]
从阿里云获取域名的记录是成功的，用SSH连接群晖用CURL访问接口也是没问题的。

**Comment by sanjusss** [comment]
可能是获取ip的网站ssl证书过期，今天晚些时候我检查一下

**Comment by vikingleo** [comment]
作者好，我出现了常见问题里那个异常，怎么处理呢？群晖docker

**Comment by li-qiang** [comment]
+1

**Comment by zzy-life** [comment]
+1

**Comment by zzy-life** [comment]
[09/19/2022 10:14:26]跳过设置域名 api.zhangzhiyu.live
[09/19/2022 10:19:10]从 淘宝接口 获取公网IPv4失败。
[09/19/2022 10:19:10]从 3322接口 获取公网IPv4失败。
[09/19/2022 10:19:10]从 test-ipv6.com接口 获取公网IPv4失败。
[09/19/2022 10:19:10]从 ip-api.com接口 获取公网IPv4失败。
[09/19/2022 10:19:10]获取公网IPv4失败，所有API接口均无法返回IPv4地址。
[09/19/2022 10:19:15]获取www.zhangzhiyu.live的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: SDK.WebException : HttpWebRequest WebException occured, the request url is alidns.aliyuncs.com System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at Aliyun.Acs.Core.Http.HttpResponse.GetResponse(HttpRequest request, Nullable`1 timeout)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, String regionId, AlibabaCloudCredentials credentials, Signer signer, Nullable`1 format, List`1 endpoints)
   at Aliyun.Acs.Core.DefaultAcsClient.DoAction[T](AcsRequest`1 request, Boolean autoRetry, Int32 maxRetryNumber, IClientProfile profile)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain)

**Comment by meimxn** [comment]
我在威联通nas的docker上部署也遇到这个问题了，之前都是正常的，有知道怎么解决的吗？[02/17/202417:26:25］从 test -ipv6.com接口获取公网IPv4失败。
[02/17/202417:26:25］从 ip-api.com 接口获取公网IPv4失败。
[02/17/202417:26:25］从3322接口获取公网IPv4失败。
[02/17/202417:26:25］获取公网IPv4失败，所有 API 接口均无法返回IPv4地址。[02/17/202417:26:25］从 ident.me 接口获取公网IPv6失败。
[02/17/202417:26:25］从 dyndns.com 接口获取公网IPv6失败。
[02/17/202417:26:25］从 ip.sb 接口获取公网IPv6失败。
[02/17/202417:26:25］从ipify.org 接口获取公网IPv6失败。
[02/17/202417:26:25］从 test-ipv6.com接口获取公网IPv6失败。
[02/17/202417:26:25］获取公网IPv6失败，所有 API 接口均无法返回IPv6地址。
