### ISSUE TITLE
二级域名无法获取记录

### ISSUE THREAD

**Issue by GeneralPanfeng** [sanjusss/aliyun-ddns#64]
[05/28/2022 13:08:38]当前公网IPv6为 2409:****:****:4175:265e:****:fe33:****（ident.me接口）。
[05/28/2022 13:08:38]获取@.test.example.cn的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: InvalidDomainName.NoExist : The specified domain name does not exist. Refresh the page and try again. + [ RequestId : 06CBE6BE-060E-57FD-A289-********** ]
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[05/28/2022 13:08:38]跳过设置域名 @.test.example.cn

**Comment by GeneralPanfeng** [comment]
我主域名托管在别处，将test.example.cn这个二级域名托管在阿里云，想单独解析ipv6，应该如何解决呢？
参数 -e "DOMAIN=@.test.example.cn" -e "TYPE=AAAA"，是不是哪里写错了？-e "DOMAIN=test.example.cn"试了一下也不行

**Comment by sanjusss** [comment]
在阿里云网站上能手动设置这个二级域名的解析吗？

**Comment by GeneralPanfeng** [comment]
可以手动设置二级域名

**Comment by GeneralPanfeng** [comment]
设置三级域名问题复现，可以在网站上手动设置test.test.example.cn。无法用自动设置test.test.example.cn，依然提示Aliyun.Acs.Core.Exceptions.ClientException: InvalidDomainName.NoExist
