### ISSUE TITLE
命令行使用报错：无效accesskeyid[Specified access key is not found or invalid.]

### ISSUE THREAD

**Issue by host2318** [sanjusss/aliyun-ddns#77]
`dotnet aliyun-ddns.dll \
[2023-05-10 14:37:58]从 ident.me接口 获取公网IPv6失败。
[2023-05-10 14:37:58]从 dyndns.com接口 获取公网IPv6失败。
[2023-05-10 14:37:58]从 ip.sb接口 获取公网IPv6失败。
[2023-05-10 14:37:58]从 ipify.org接口 获取公网IPv6失败。
[2023-05-10 14:37:58]从 test-ipv6.com接口 获取公网IPv6失败。
[2023-05-10 14:37:58]获取公网IPv6失败，所有API接口均无法返回IPv6地址。
[2023-05-10 14:37:58]当前公网IPv4为 113.68.68.68（3322接口）。#此IP为杜撰虚假IP
[2023-05-10 14:37:58]获取my.domain.com的所有记录时出现异常：Aliyun.Acs.Core.Exceptions.ClientException: InvalidAccessKeyId : Specified access key is not found or invalid. + [ RequestId : 0E0AC82F-B026-5C39-91F4-B7E63A2D1332 ]
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at aliyun_ddns.DomainUpdater.GetRecords(String domain)
[2023-05-10 14:37:58]跳过设置域名 my.domain.com`

在网上 搜索有反馈：
https://developer.aliyun.com/ask/109402

我的keyid 确定无误，且拿其他正常使用的项目key替换，依然报错

**Comment by l378500947** [comment]
我也遇到了同样的问题，我确认我的AccessKeyId没有填错，也没有加多余的符号，我的设备是openwrt

**Comment by victor-wen** [comment]
我也是 不知道怎么解决
