### ISSUE TITLE
无法获取ipv6地址

### ISSUE THREAD

**Issue by rongjieaaa** [sanjusss/aliyun-ddns#90]
以docker容器运行：
    docker run -it --restart=always --net=host --name test \
    -e "AKID=xxxxx" \
    -e "AKSCT=xxxxxx" \
    -e "DOMAIN=xxxxxx" \
    sanjusss/aliyun-ddns

返回的结果：
[06/21/2024 10:08:08]当前公网IPv4为 xxx.xxx.xxx.xxx（3322接口）。
[06/21/2024 10:08:38]获取公网IPv6失败，所有API接口均无法返回IPv6地址。
[06/21/2024 10:08:38]从 ipify.org接口 获取公网IPv6失败。
[06/21/2024 10:08:38]从 dyndns.com接口 获取公网IPv6失败。
[06/21/2024 10:08:38]从 ip.sb接口 获取公网IPv6失败。
[06/21/2024 10:08:38]从 ident.me接口 获取公网IPv6失败。
[06/21/2024 10:08:38]从 test-ipv6.com接口 获取公网IPv6失败。
[06/21/2024 10:08:40]成功获取test.xxxxxx.com的所有记录，共0条。
[06/21/2024 10:08:40]成功增加A记录test.xxxxxx.com为xxx.xxx.xxx。
[06/21/2024 10:08:41]增加AAAA记录test.xxxxxx.com时发生异常： Aliyun.Acs.Core.Exceptions.ClientException: MissingValue : Value is mandatory for this action. + [ RequestId : 1220ADED-206D-53B0-9CAA-161D716A3E13 ]
   at Aliyun.Acs.Core.DefaultAcsClient.ParseAcsResponse[T](AcsRequest`1 request, HttpResponse httpResponse)
   at Aliyun.Acs.Core.DefaultAcsClient.GetAcsResponse[T](AcsRequest`1 request)
   at aliyun_ddns.DomainUpdater.AddRecord(IpType type, String domain, String ip)

**Comment by zhespace** [comment]
你好，我原来也是，bridge改成host重启一下就可以了
